GLOB sdist-make: /home/mraful/PycharmProjects/libcloud/setup.py
py2.7 inst-nodeps: /home/mraful/PycharmProjects/libcloud/.tox/dist/apache-libcloud-2.3.0.zip
py2.7 installed: apache-libcloud==2.3.0,asn1crypto==0.24.0,astroid==1.4.9,attrs==18.2.0,bcrypt==3.1.4,certifi==2018.8.24,cffi==1.11.5,chardet==3.0.4,codecov==2.0.15,colorama==0.3.9,coverage==3.7.1,cryptography==2.3.1,enum34==1.1.6,flake8==2.5.5,funcsigs==1.0.2,idna==2.7,ipaddress==1.0.22,lazy-object-proxy==1.3.1,libvirt-python==4.0.0,lockfile==0.12.2,mccabe==0.4.0,mock==1.0.1,paramiko==2.4.2,pep8==1.7.1,pluggy==0.6.0,py==1.6.0,pyasn1==0.4.4,pycparser==2.19,pyflakes==1.0.0,pylint==1.5.6,PyNaCl==1.3.0,pytest==3.4.2,requests==2.19.1,requests-mock==1.5.2,six==1.11.0,urllib3==1.23,wrapt==1.10.11
py2.7 run-test-pre: PYTHONHASHSEED='1624183434'
py2.7 runtests: commands[0] | cp libcloud/test/secrets.py-dist libcloud/test/secrets.py
py2.7 runtests: commands[1] | python setup.py test
running pytest
running egg_info
writing dependency_links to apache_libcloud.egg-info/dependency_links.txt
writing apache_libcloud.egg-info/PKG-INFO
writing top-level names to apache_libcloud.egg-info/top_level.txt
writing requirements to apache_libcloud.egg-info/requires.txt
reading manifest file 'apache_libcloud.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'libcloud/test/secrets.py'
writing manifest file 'apache_libcloud.egg-info/SOURCES.txt'
running build_ext
============================= test session starts ==============================
platform linux2 -- Python 2.7.15rc1, pytest-3.4.2, py-1.6.0, pluggy-0.6.0
rootdir: /home/mraful/PycharmProjects/libcloud, inifile: pytest.ini
plugins: requests-mock-1.5.2
collected 6162 items / 16 errors

==================================== ERRORS ====================================
_____________ ERROR collecting libcloud/test/compute/test_bsnl.py ______________
.tox/py2.7/local/lib/python2.7/site-packages/_pytest/python.py:411: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
.tox/py2.7/local/lib/python2.7/site-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
.tox/py2.7/local/lib/python2.7/site-packages/_pytest/assertion/rewrite.py:213: in load_module
    py.builtin.exec_(co, mod.__dict__)
libcloud/test/compute/test_bsnl.py:18: in <module>
    from libcloud.compute.drivers.bsnl import BSNLNodeDriver
libcloud/compute/drivers/bsnl.py:19: in <module>
    from libcloud.compute.drivers.dimensiondata import DimensionDataNodeDriver
E     File "/home/mraful/PycharmProjects/libcloud/libcloud/compute/drivers/dimensiondata.py", line 3070
E       def ex_list_ip_address_list(self, ex_network_domain: object) -> object:
E                                                          ^
E   SyntaxError: invalid syntax
______ ERROR collecting libcloud/test/compute/test_dimensiondata_v2_3.py _______
.tox/py2.7/local/lib/python2.7/site-packages/_pytest/python.py:411: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
.tox/py2.7/local/lib/python2.7/site-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
.tox/py2.7/local/lib/python2.7/site-packages/_pytest/assertion/rewrite.py:213: in load_module
    py.builtin.exec_(co, mod.__dict__)
libcloud/test/compute/test_dimensiondata_v2_3.py:28: in <module>
    from libcloud.compute.drivers.dimensiondata import DimensionDataNodeDriver as DimensionData
E     File "/home/mraful/PycharmProjects/libcloud/libcloud/compute/drivers/dimensiondata.py", line 3070
E       def ex_list_ip_address_list(self, ex_network_domain: object) -> object:
E                                                          ^
E   SyntaxError: invalid syntax
______ ERROR collecting libcloud/test/compute/test_dimensiondata_v2_4.py _______
.tox/py2.7/local/lib/python2.7/site-packages/_pytest/python.py:411: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
.tox/py2.7/local/lib/python2.7/site-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
.tox/py2.7/local/lib/python2.7/site-packages/_pytest/assertion/rewrite.py:213: in load_module
    py.builtin.exec_(co, mod.__dict__)
libcloud/test/compute/test_dimensiondata_v2_4.py:28: in <module>
    from libcloud.compute.drivers.dimensiondata import DimensionDataNodeDriver as DimensionData
E     File "/home/mraful/PycharmProjects/libcloud/libcloud/compute/drivers/dimensiondata.py", line 3070
E       def ex_list_ip_address_list(self, ex_network_domain: object) -> object:
E                                                          ^
E   SyntaxError: invalid syntax
____________ ERROR collecting libcloud/test/compute/test_indosat.py ____________
.tox/py2.7/local/lib/python2.7/site-packages/_pytest/python.py:411: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
.tox/py2.7/local/lib/python2.7/site-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
.tox/py2.7/local/lib/python2.7/site-packages/_pytest/assertion/rewrite.py:213: in load_module
    py.builtin.exec_(co, mod.__dict__)
libcloud/test/compute/test_indosat.py:18: in <module>
    from libcloud.compute.drivers.indosat import IndosatNodeDriver
libcloud/compute/drivers/indosat.py:22: in <module>
    from libcloud.compute.drivers.dimensiondata import DimensionDataNodeDriver
E     File "/home/mraful/PycharmProjects/libcloud/libcloud/compute/drivers/dimensiondata.py", line 3070
E       def ex_list_ip_address_list(self, ex_network_domain: object) -> object:
E                                                          ^
E   SyntaxError: invalid syntax
_______ ERROR collecting libcloud/test/compute/test_internetsolutions.py _______
.tox/py2.7/local/lib/python2.7/site-packages/_pytest/python.py:411: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
.tox/py2.7/local/lib/python2.7/site-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
.tox/py2.7/local/lib/python2.7/site-packages/_pytest/assertion/rewrite.py:213: in load_module
    py.builtin.exec_(co, mod.__dict__)
libcloud/test/compute/test_internetsolutions.py:18: in <module>
    from libcloud.compute.drivers.internetsolutions import InternetSolutionsNodeDriver
libcloud/compute/drivers/internetsolutions.py:22: in <module>
    from libcloud.compute.drivers.dimensiondata import DimensionDataNodeDriver
E     File "/home/mraful/PycharmProjects/libcloud/libcloud/compute/drivers/dimensiondata.py", line 3070
E       def ex_list_ip_address_list(self, ex_network_domain: object) -> object:
E                                                          ^
E   SyntaxError: invalid syntax
____________ ERROR collecting libcloud/test/compute/test_medone.py _____________
.tox/py2.7/local/lib/python2.7/site-packages/_pytest/python.py:411: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
.tox/py2.7/local/lib/python2.7/site-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
.tox/py2.7/local/lib/python2.7/site-packages/_pytest/assertion/rewrite.py:213: in load_module
    py.builtin.exec_(co, mod.__dict__)
libcloud/test/compute/test_medone.py:18: in <module>
    from libcloud.compute.drivers.medone import MedOneNodeDriver
libcloud/compute/drivers/medone.py:22: in <module>
    from libcloud.compute.drivers.dimensiondata import DimensionDataNodeDriver
E     File "/home/mraful/PycharmProjects/libcloud/libcloud/compute/drivers/dimensiondata.py", line 3070
E       def ex_list_ip_address_list(self, ex_network_domain: object) -> object:
E                                                          ^
E   SyntaxError: invalid syntax
_____________ ERROR collecting libcloud/test/compute/test_ntta.py ______________
.tox/py2.7/local/lib/python2.7/site-packages/_pytest/python.py:411: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
.tox/py2.7/local/lib/python2.7/site-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
.tox/py2.7/local/lib/python2.7/site-packages/_pytest/assertion/rewrite.py:213: in load_module
    py.builtin.exec_(co, mod.__dict__)
libcloud/test/compute/test_ntta.py:18: in <module>
    from libcloud.compute.drivers.ntta import NTTAmericaNodeDriver
libcloud/compute/drivers/ntta.py:22: in <module>
    from libcloud.compute.drivers.dimensiondata import DimensionDataNodeDriver
E     File "/home/mraful/PycharmProjects/libcloud/libcloud/compute/drivers/dimensiondata.py", line 3070
E       def ex_list_ip_address_list(self, ex_network_domain: object) -> object:
E                                                          ^
E   SyntaxError: invalid syntax
________ ERROR collecting libcloud/test/loadbalancer/test_brightbox.py _________
libcloud/test/loadbalancer/test_brightbox.py:21: in <module>
    from libcloud.loadbalancer.drivers.brightbox import BrightboxLBDriver
libcloud/loadbalancer/drivers/brightbox.py:27: in <module>
    class BrightboxLBDriver(Driver):
libcloud/loadbalancer/drivers/brightbox.py:44: in BrightboxLBDriver
    'least-connections': Algorithm.LEAST_CONNECTIONS
E   AttributeError: type object 'Algorithm' has no attribute 'LEAST_CONNECTIONS'
________ ERROR collecting libcloud/test/loadbalancer/test_cloudstack.py ________
libcloud/test/loadbalancer/test_cloudstack.py:15: in <module>
    from libcloud.loadbalancer.drivers.cloudstack import CloudStackLBDriver
libcloud/loadbalancer/drivers/cloudstack.py:24: in <module>
    class CloudStackLBDriver(CloudStackDriverMixIn, Driver):
libcloud/loadbalancer/drivers/cloudstack.py:34: in CloudStackLBDriver
    'leastconn': Algorithm.LEAST_CONNECTIONS
E   AttributeError: type object 'Algorithm' has no attribute 'LEAST_CONNECTIONS'
____ ERROR collecting libcloud/test/loadbalancer/test_dimensiondata_v2_3.py ____
libcloud/test/loadbalancer/test_dimensiondata_v2_3.py:22: in <module>
    from libcloud.loadbalancer.drivers.dimensiondata \
libcloud/loadbalancer/drivers/dimensiondata.py:38: in <module>
    class DimensionDataLBDriver(Driver):
libcloud/loadbalancer/drivers/dimensiondata.py:54: in DimensionDataLBDriver
    'LEAST_CONNECTIONS': Algorithm.LEAST_CONNECTIONS,
E   AttributeError: type object 'Algorithm' has no attribute 'LEAST_CONNECTIONS'
____ ERROR collecting libcloud/test/loadbalancer/test_dimensiondata_v2_4.py ____
libcloud/test/loadbalancer/test_dimensiondata_v2_4.py:22: in <module>
    from libcloud.loadbalancer.drivers.dimensiondata \
libcloud/loadbalancer/drivers/dimensiondata.py:38: in <module>
    class DimensionDataLBDriver(Driver):
libcloud/loadbalancer/drivers/dimensiondata.py:54: in DimensionDataLBDriver
    'LEAST_CONNECTIONS': Algorithm.LEAST_CONNECTIONS,
E   AttributeError: type object 'Algorithm' has no attribute 'LEAST_CONNECTIONS'
___________ ERROR collecting libcloud/test/loadbalancer/test_gce.py ____________
libcloud/test/loadbalancer/test_gce.py:23: in <module>
    from libcloud.loadbalancer.drivers.gce import (GCELBDriver)
libcloud/loadbalancer/drivers/gce.py:27: in <module>
    DEFAULT_ALGORITHM = Algorithm.RANDOM
E   AttributeError: type object 'Algorithm' has no attribute 'RANDOM'
__________ ERROR collecting libcloud/test/loadbalancer/test_gogrid.py __________
libcloud/test/loadbalancer/test_gogrid.py:26: in <module>
    from libcloud.loadbalancer.drivers.gogrid import GoGridLBDriver
libcloud/loadbalancer/drivers/gogrid.py:58: in <module>
    class GoGridLBDriver(BaseGoGridDriver, Driver):
libcloud/loadbalancer/drivers/gogrid.py:68: in GoGridLBDriver
    'least connect': Algorithm.LEAST_CONNECTIONS
E   AttributeError: type object 'Algorithm' has no attribute 'LEAST_CONNECTIONS'
________ ERROR collecting libcloud/test/loadbalancer/test_rackspace.py _________
libcloud/test/loadbalancer/test_rackspace.py:29: in <module>
    from libcloud.loadbalancer.drivers.rackspace import RackspaceLBDriver, \
libcloud/loadbalancer/drivers/rackspace.py:284: in <module>
    class RackspaceLBDriver(Driver, OpenStackDriverMixin):
libcloud/loadbalancer/drivers/rackspace.py:308: in RackspaceLBDriver
    'RANDOM': Algorithm.RANDOM,
E   AttributeError: type object 'Algorithm' has no attribute 'RANDOM'
___________ ERROR collecting libcloud/test/loadbalancer/test_slb.py ____________
libcloud/test/loadbalancer/test_slb.py:22: in <module>
    from libcloud.loadbalancer.drivers.slb import SLBDriver, \
libcloud/loadbalancer/drivers/slb.py:88: in <module>
    'wrr': Algorithm.WEIGHTED_ROUND_ROBIN,
E   AttributeError: type object 'Algorithm' has no attribute 'WEIGHTED_ROUND_ROBIN'
________ ERROR collecting libcloud/test/loadbalancer/test_softlayer.py _________
libcloud/test/loadbalancer/test_softlayer.py:24: in <module>
    from libcloud.loadbalancer.drivers.softlayer import SoftlayerLBDriver
libcloud/loadbalancer/drivers/softlayer.py:69: in <module>
    class SoftlayerLBDriver(Driver):
libcloud/loadbalancer/drivers/softlayer.py:76: in SoftlayerLBDriver
    'LEAST_CONNECTIONS': Algorithm.LEAST_CONNECTIONS,
E   AttributeError: type object 'Algorithm' has no attribute 'LEAST_CONNECTIONS'
!!!!!!!!!!!!!!!!!!! Interrupted: 16 errors during collection !!!!!!!!!!!!!!!!!!!
=========================== 16 error in 3.08 seconds ===========================
ERROR: InvocationError for command '/home/mraful/PycharmProjects/libcloud/.tox/py2.7/bin/python setup.py test' (exited with code 2)
pypypy create: /home/mraful/PycharmProjects/libcloud/.tox/pypypy
ERROR: InterpreterNotFound: pypy
pypypy3 create: /home/mraful/PycharmProjects/libcloud/.tox/pypypy3
ERROR: InterpreterNotFound: pypy3
py3.4 create: /home/mraful/PycharmProjects/libcloud/.tox/py3.4
ERROR: InterpreterNotFound: python3.4
py3.5 create: /home/mraful/PycharmProjects/libcloud/.tox/py3.5
ERROR: InterpreterNotFound: python3.5
py3.6 inst-nodeps: /home/mraful/PycharmProjects/libcloud/.tox/dist/apache-libcloud-2.3.0.zip
py3.6 installed: apache-libcloud==2.3.0,astroid==1.4.9,attrs==18.2.0,certifi==2018.8.24,chardet==3.0.4,codecov==2.0.15,colorama==0.3.9,coverage==3.7.1,flake8==2.5.5,idna==2.7,lazy-object-proxy==1.3.1,libvirt-python==4.0.0,lockfile==0.12.2,mccabe==0.4.0,mock==1.0.1,pep8==1.7.1,pluggy==0.6.0,py==1.6.0,pyflakes==1.0.0,pylint==1.5.6,pytest==3.4.2,requests==2.19.1,requests-mock==1.5.2,six==1.11.0,urllib3==1.23,wrapt==1.10.11
py3.6 run-test-pre: PYTHONHASHSEED='1624183434'
py3.6 runtests: commands[0] | cp libcloud/test/secrets.py-dist libcloud/test/secrets.py
py3.6 runtests: commands[1] | python setup.py test
running pytest
running egg_info
writing apache_libcloud.egg-info/PKG-INFO
writing dependency_links to apache_libcloud.egg-info/dependency_links.txt
writing requirements to apache_libcloud.egg-info/requires.txt
writing top-level names to apache_libcloud.egg-info/top_level.txt
reading manifest file 'apache_libcloud.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'libcloud/test/secrets.py'
writing manifest file 'apache_libcloud.egg-info/SOURCES.txt'
running build_ext
============================= test session starts ==============================
platform linux -- Python 3.6.5, pytest-3.4.2, py-1.6.0, pluggy-0.6.0
rootdir: /home/mraful/PycharmProjects/libcloud, inifile: pytest.ini
plugins: requests-mock-1.5.2
collected 8794 items / 9 errors

==================================== ERRORS ====================================
________ ERROR collecting libcloud/test/loadbalancer/test_brightbox.py _________
libcloud/test/loadbalancer/test_brightbox.py:21: in <module>
    from libcloud.loadbalancer.drivers.brightbox import BrightboxLBDriver
libcloud/loadbalancer/drivers/brightbox.py:27: in <module>
    class BrightboxLBDriver(Driver):
libcloud/loadbalancer/drivers/brightbox.py:44: in BrightboxLBDriver
    'least-connections': Algorithm.LEAST_CONNECTIONS
E   AttributeError: type object 'Algorithm' has no attribute 'LEAST_CONNECTIONS'
________ ERROR collecting libcloud/test/loadbalancer/test_cloudstack.py ________
libcloud/test/loadbalancer/test_cloudstack.py:15: in <module>
    from libcloud.loadbalancer.drivers.cloudstack import CloudStackLBDriver
libcloud/loadbalancer/drivers/cloudstack.py:24: in <module>
    class CloudStackLBDriver(CloudStackDriverMixIn, Driver):
libcloud/loadbalancer/drivers/cloudstack.py:34: in CloudStackLBDriver
    'leastconn': Algorithm.LEAST_CONNECTIONS
E   AttributeError: type object 'Algorithm' has no attribute 'LEAST_CONNECTIONS'
____ ERROR collecting libcloud/test/loadbalancer/test_dimensiondata_v2_3.py ____
libcloud/test/loadbalancer/test_dimensiondata_v2_3.py:22: in <module>
    from libcloud.loadbalancer.drivers.dimensiondata \
libcloud/loadbalancer/drivers/dimensiondata.py:38: in <module>
    class DimensionDataLBDriver(Driver):
libcloud/loadbalancer/drivers/dimensiondata.py:54: in DimensionDataLBDriver
    'LEAST_CONNECTIONS': Algorithm.LEAST_CONNECTIONS,
E   AttributeError: type object 'Algorithm' has no attribute 'LEAST_CONNECTIONS'
____ ERROR collecting libcloud/test/loadbalancer/test_dimensiondata_v2_4.py ____
libcloud/test/loadbalancer/test_dimensiondata_v2_4.py:22: in <module>
    from libcloud.loadbalancer.drivers.dimensiondata \
libcloud/loadbalancer/drivers/dimensiondata.py:38: in <module>
    class DimensionDataLBDriver(Driver):
libcloud/loadbalancer/drivers/dimensiondata.py:54: in DimensionDataLBDriver
    'LEAST_CONNECTIONS': Algorithm.LEAST_CONNECTIONS,
E   AttributeError: type object 'Algorithm' has no attribute 'LEAST_CONNECTIONS'
___________ ERROR collecting libcloud/test/loadbalancer/test_gce.py ____________
libcloud/test/loadbalancer/test_gce.py:23: in <module>
    from libcloud.loadbalancer.drivers.gce import (GCELBDriver)
libcloud/loadbalancer/drivers/gce.py:27: in <module>
    DEFAULT_ALGORITHM = Algorithm.RANDOM
E   AttributeError: type object 'Algorithm' has no attribute 'RANDOM'
__________ ERROR collecting libcloud/test/loadbalancer/test_gogrid.py __________
libcloud/test/loadbalancer/test_gogrid.py:26: in <module>
    from libcloud.loadbalancer.drivers.gogrid import GoGridLBDriver
libcloud/loadbalancer/drivers/gogrid.py:58: in <module>
    class GoGridLBDriver(BaseGoGridDriver, Driver):
libcloud/loadbalancer/drivers/gogrid.py:68: in GoGridLBDriver
    'least connect': Algorithm.LEAST_CONNECTIONS
E   AttributeError: type object 'Algorithm' has no attribute 'LEAST_CONNECTIONS'
________ ERROR collecting libcloud/test/loadbalancer/test_rackspace.py _________
libcloud/test/loadbalancer/test_rackspace.py:29: in <module>
    from libcloud.loadbalancer.drivers.rackspace import RackspaceLBDriver, \
libcloud/loadbalancer/drivers/rackspace.py:284: in <module>
    class RackspaceLBDriver(Driver, OpenStackDriverMixin):
libcloud/loadbalancer/drivers/rackspace.py:308: in RackspaceLBDriver
    'RANDOM': Algorithm.RANDOM,
E   AttributeError: type object 'Algorithm' has no attribute 'RANDOM'
___________ ERROR collecting libcloud/test/loadbalancer/test_slb.py ____________
libcloud/test/loadbalancer/test_slb.py:22: in <module>
    from libcloud.loadbalancer.drivers.slb import SLBDriver, \
libcloud/loadbalancer/drivers/slb.py:88: in <module>
    'wrr': Algorithm.WEIGHTED_ROUND_ROBIN,
E   AttributeError: type object 'Algorithm' has no attribute 'WEIGHTED_ROUND_ROBIN'
________ ERROR collecting libcloud/test/loadbalancer/test_softlayer.py _________
libcloud/test/loadbalancer/test_softlayer.py:24: in <module>
    from libcloud.loadbalancer.drivers.softlayer import SoftlayerLBDriver
libcloud/loadbalancer/drivers/softlayer.py:69: in <module>
    class SoftlayerLBDriver(Driver):
libcloud/loadbalancer/drivers/softlayer.py:76: in SoftlayerLBDriver
    'LEAST_CONNECTIONS': Algorithm.LEAST_CONNECTIONS,
E   AttributeError: type object 'Algorithm' has no attribute 'LEAST_CONNECTIONS'
!!!!!!!!!!!!!!!!!!! Interrupted: 9 errors during collection !!!!!!!!!!!!!!!!!!!!
=========================== 9 error in 2.52 seconds ============================
ERROR: InvocationError for command '/home/mraful/PycharmProjects/libcloud/.tox/py3.6/bin/python setup.py test' (exited with code 2)
checks inst-nodeps: /home/mraful/PycharmProjects/libcloud/.tox/dist/apache-libcloud-2.3.0.zip
checks installed: apache-libcloud==2.3.0,astroid==1.4.9,attrs==18.2.0,certifi==2018.8.24,chardet==3.0.4,codecov==2.0.15,colorama==0.3.9,coverage==3.7.1,flake8==2.5.5,funcsigs==1.0.2,idna==2.7,lazy-object-proxy==1.3.1,libvirt-python==4.0.0,lockfile==0.12.2,mccabe==0.4.0,mock==1.0.1,pep8==1.7.1,pluggy==0.6.0,py==1.6.0,pyflakes==1.0.0,pylint==1.5.6,pytest==3.4.2,requests==2.19.1,requests-mock==1.5.2,six==1.11.0,urllib3==1.23,wrapt==1.10.11
checks run-test-pre: PYTHONHASHSEED='1624183434'
checks runtests: commands[0] | bash ./scripts/check_file_names.sh
lint inst-nodeps: /home/mraful/PycharmProjects/libcloud/.tox/dist/apache-libcloud-2.3.0.zip
lint installed: apache-libcloud==2.3.0,astroid==1.4.9,attrs==18.2.0,backports.ssl-match-hostname==3.5.0.1,certifi==2018.8.24,chardet==3.0.4,codecov==2.0.15,colorama==0.3.9,coverage==3.7.1,flake8==2.5.5,funcsigs==1.0.2,idna==2.7,lazy-object-proxy==1.3.1,lockfile==0.12.2,mccabe==0.4.0,mock==1.0.1,pep8==1.7.1,pluggy==0.6.0,py==1.6.0,pyflakes==1.0.0,pylint==1.5.6,pytest==3.4.2,requests==2.19.1,requests-mock==1.5.2,six==1.11.0,urllib3==1.23,wrapt==1.10.11
lint run-test-pre: PYTHONHASHSEED='1624183434'
lint runtests: commands[0] | flake8 --ignore=E402 --exclude=test libcloud/
libcloud/http.py:225:5: E303 too many blank lines (2)
libcloud/utils/xml.py:28:5: F841 local variable 'path' is assigned to but never used
libcloud/common/nttcis.py:815:27: E901 SyntaxError: invalid syntax
libcloud/loadbalancer/drivers/nttcis.py:200:51: E901 SyntaxError: invalid syntax
libcloud/loadbalancer/drivers/nttcis.py:211:80: E501 line too long (85 > 79 characters)
libcloud/compute/drivers/dimensiondata.py:3070:57: E901 SyntaxError: invalid syntax
libcloud/compute/drivers/dimensiondata.py:4498:13: E265 block comment should start with '# '
libcloud/compute/drivers/dimensiondata.py:4504:17: E122 continuation line missing indentation or outdented
libcloud/compute/drivers/dimensiondata.py:4505:17: E122 continuation line missing indentation or outdented
libcloud/compute/drivers/dimensiondata.py:4506:17: E122 continuation line missing indentation or outdented
libcloud/compute/drivers/nttcis.py:840:51: E901 SyntaxError: invalid syntax
libcloud/compute/drivers/nttcis.py:897:15: E271 multiple spaces after keyword
libcloud/compute/drivers/nttcis.py:897:80: E501 line too long (100 > 79 characters)
libcloud/compute/drivers/nttcis.py:1019:17: E125 continuation line with same indent as next logical line
libcloud/compute/drivers/nttcis.py:1127:80: E501 line too long (92 > 79 characters)
libcloud/compute/drivers/nttcis.py:1327:80: E501 line too long (80 > 79 characters)
libcloud/compute/drivers/nttcis.py:1328:37: E127 continuation line over-indented for visual indent
libcloud/compute/drivers/nttcis.py:1370:27: E126 continuation line over-indented for hanging indent
libcloud/compute/drivers/nttcis.py:1373:27: E126 continuation line over-indented for hanging indent
libcloud/compute/drivers/nttcis.py:1375:23: E127 continuation line over-indented for visual indent
libcloud/compute/drivers/nttcis.py:1377:23: E127 continuation line over-indented for visual indent
libcloud/compute/drivers/nttcis.py:1380:27: E126 continuation line over-indented for hanging indent
libcloud/compute/drivers/nttcis.py:1400:37: E128 continuation line under-indented for visual indent
libcloud/compute/drivers/nttcis.py:1447:9: E265 block comment should start with '# '
libcloud/compute/drivers/nttcis.py:1991:61: E126 continuation line over-indented for hanging indent
libcloud/compute/drivers/nttcis.py:2040:5: E303 too many blank lines (2)
libcloud/compute/drivers/nttcis.py:2058:59: E126 continuation line over-indented for hanging indent
libcloud/compute/drivers/nttcis.py:2062:59: E123 closing bracket does not match indentation of opening bracket's line
libcloud/compute/drivers/nttcis.py:2080:38: E126 continuation line over-indented for hanging indent
libcloud/compute/drivers/nttcis.py:2086:36: E241 multiple spaces after ','
libcloud/compute/drivers/nttcis.py:2103:43: E126 continuation line over-indented for hanging indent
libcloud/compute/drivers/nttcis.py:2104:13: E122 continuation line missing indentation or outdented
libcloud/compute/drivers/nttcis.py:2109:36: E241 multiple spaces after ','
libcloud/compute/drivers/nttcis.py:2126:43: E126 continuation line over-indented for hanging indent
libcloud/compute/drivers/nttcis.py:2150:1: W293 blank line contains whitespace
libcloud/compute/drivers/nttcis.py:2173:1: W293 blank line contains whitespace
libcloud/compute/drivers/nttcis.py:2265:54: W291 trailing whitespace
libcloud/compute/drivers/nttcis.py:2504:80: E501 line too long (82 > 79 characters)
libcloud/compute/drivers/nttcis.py:2778:61: W291 trailing whitespace
libcloud/compute/drivers/nttcis.py:2826:64: W291 trailing whitespace
libcloud/compute/drivers/nttcis.py:2836:63: W291 trailing whitespace
libcloud/compute/drivers/nttcis.py:2837:63: W291 trailing whitespace
libcloud/compute/drivers/nttcis.py:2930:9: E265 block comment should start with '# '
libcloud/compute/drivers/nttcis.py:2971:72: W291 trailing whitespace
libcloud/compute/drivers/nttcis.py:3041:1: W293 blank line contains whitespace
libcloud/compute/drivers/nttcis.py:3262:64: W291 trailing whitespace
libcloud/compute/drivers/nttcis.py:3563:38: W291 trailing whitespace
libcloud/compute/drivers/nttcis.py:3564:50: E231 missing whitespace after ':'
libcloud/compute/drivers/nttcis.py:3565:9: E125 continuation line with same indent as next logical line
libcloud/compute/drivers/nttcis.py:3790:47: W291 trailing whitespace
libcloud/compute/drivers/nttcis.py:3791:52: W291 trailing whitespace
libcloud/compute/drivers/nttcis.py:4867:60: E126 continuation line over-indented for hanging indent
libcloud/compute/drivers/nttcis.py:4970:36: E124 closing bracket does not match visual indentation
libcloud/compute/drivers/nttcis.py:4993:30: E231 missing whitespace after ':'
libcloud/compute/drivers/nttcis.py:5001:10: E111 indentation is not a multiple of four
libcloud/compute/drivers/nttcis.py:5002:10: E111 indentation is not a multiple of four
libcloud/compute/drivers/nttcis.py:5005:10: E111 indentation is not a multiple of four
libcloud/compute/drivers/nttcis.py:5005:80: E501 line too long (91 > 79 characters)
libcloud/compute/drivers/nttcis.py:5006:10: E111 indentation is not a multiple of four
libcloud/compute/drivers/nttcis.py:5009:15: E271 multiple spaces after keyword
libcloud/compute/drivers/nttcis.py:5010:41: E126 continuation line over-indented for hanging indent
libcloud/compute/drivers/nttcis.py:5013:80: E501 line too long (82 > 79 characters)
libcloud/compute/drivers/nttcis.py:5014:53: E251 unexpected spaces around keyword / parameter equals
libcloud/compute/drivers/nttcis.py:5015:80: E501 line too long (85 > 79 characters)
libcloud/compute/drivers/nttcis.py:5023:10: E111 indentation is not a multiple of four
libcloud/compute/drivers/nttcis.py:5023:80: E501 line too long (82 > 79 characters)
libcloud/compute/drivers/nttcis.py:5053:37: E126 continuation line over-indented for hanging indent
libcloud/compute/drivers/nttcis.py:5055:41: E122 continuation line missing indentation or outdented
libcloud/compute/drivers/nttcis.py:5076:13: E265 block comment should start with '# '
libcloud/compute/drivers/nttcis.py:5082:17: E122 continuation line missing indentation or outdented
libcloud/compute/drivers/nttcis.py:5083:17: E122 continuation line missing indentation or outdented
libcloud/compute/drivers/nttcis.py:5084:17: E122 continuation line missing indentation or outdented
libcloud/compute/drivers/nttcis.py:5102:24: E131 continuation line unaligned for hanging indent
libcloud/compute/drivers/nttcis.py:5157:57: E126 continuation line over-indented for hanging indent
libcloud/compute/drivers/nttcis.py:5161:49: E126 continuation line over-indented for hanging indent
libcloud/drs/base.py:6:61: E241 multiple spaces after ','
libcloud/drs/base.py:6:80: E501 line too long (113 > 79 characters)
libcloud/drs/base.py:38:33: W292 no newline at end of file
libcloud/drs/providers.py:41:60: W292 no newline at end of file
libcloud/drs/drivers/nttcis.py:1:1: F401 'ET' imported but unused
libcloud/drs/drivers/nttcis.py:3:1: F401 'NttCisPool' imported but unused
libcloud/drs/drivers/nttcis.py:4:1: F401 'NttCisPoolMember' imported but unused
libcloud/drs/drivers/nttcis.py:5:1: F401 'NttCisVirtualListener' imported but unused
libcloud/drs/drivers/nttcis.py:6:1: F401 'NttCisVIPNode' imported but unused
libcloud/drs/drivers/nttcis.py:7:1: F401 'NttCisDefaultHealthMonitor' imported but unused
libcloud/drs/drivers/nttcis.py:8:1: F401 'NttCisPersistenceProfile' imported but unused
libcloud/drs/drivers/nttcis.py:9:1: F401 'NttCisVirtualListenerCompatibility' imported but unused
libcloud/drs/drivers/nttcis.py:11:1: F401 'NttCisDefaultiRule' imported but unused
libcloud/drs/drivers/nttcis.py:14:1: F401 'TYPES_URN' imported but unused
libcloud/drs/drivers/nttcis.py:15:1: F401 'reverse_dict' imported but unused
libcloud/drs/drivers/nttcis.py:16:1: F401 'findall' imported but unused
libcloud/drs/drivers/nttcis.py:16:1: F401 'findtext' imported but unused
libcloud/drs/drivers/nttcis.py:16:1: F401 'fixxpath' imported but unused
libcloud/drs/drivers/nttcis.py:17:1: F401 'State' imported but unused
libcloud/drs/drivers/nttcis.py:18:1: F401 'Algorithm' imported but unused
libcloud/drs/drivers/nttcis.py:18:1: F401 'LoadBalancer' imported but unused
libcloud/drs/drivers/nttcis.py:19:1: F401 'Member' imported but unused
libcloud/drs/drivers/nttcis.py:47:53: E127 continuation line over-indented for visual indent
libcloud/drs/drivers/nttcis.py:48:53: E127 continuation line over-indented for visual indent
libcloud/drs/drivers/nttcis.py:49:53: E127 continuation line over-indented for visual indent
libcloud/drs/drivers/nttcis.py:50:53: E127 continuation line over-indented for visual indent
libcloud/drs/drivers/nttcis.py:51:53: E127 continuation line over-indented for visual indent
ERROR: InvocationError for command '/home/mraful/PycharmProjects/libcloud/.tox/lint/bin/flake8 --ignore=E402 --exclude=test libcloud/' (exited with code 1)
pylint inst-nodeps: /home/mraful/PycharmProjects/libcloud/.tox/dist/apache-libcloud-2.3.0.zip
pylint installed: apache-libcloud==2.3.0,astroid==1.4.9,attrs==18.2.0,backports.ssl-match-hostname==3.5.0.1,bottle==0.12.13,certifi==2018.8.24,chardet==3.0.4,codecov==2.0.15,colorama==0.3.9,coverage==3.7.1,flake8==2.5.5,funcsigs==1.0.2,idna==2.7,lazy-object-proxy==1.3.1,lockfile==0.12.2,mccabe==0.4.0,mock==1.0.1,pep8==1.7.1,pluggy==0.6.0,py==1.6.0,pyflakes==1.0.0,pylint==1.5.6,pytest==3.4.2,requests==2.19.1,requests-mock==1.5.2,six==1.11.0,urllib3==1.23,wrapt==1.10.11
pylint run-test-pre: PYTHONHASHSEED='1624183434'
pylint runtests: commands[0] | pylint -E --rcfile=./.pylintrc libcloud/common/
************* Module libcloud.common.nttcis
E:815, 0: invalid syntax (syntax-error)
ERROR: InvocationError for command '/home/mraful/PycharmProjects/libcloud/.tox/pylint/bin/pylint -E --rcfile=./.pylintrc libcloud/common/' (exited with code 2)
integration create: /home/mraful/PycharmProjects/libcloud/.tox/integration
ERROR: InterpreterNotFound: 
coverage inst-nodeps: /home/mraful/PycharmProjects/libcloud/.tox/dist/apache-libcloud-2.3.0.zip
coverage installed: apache-libcloud==2.3.0,astroid==1.4.9,attrs==18.2.0,certifi==2018.8.24,chardet==3.0.4,codecov==2.0.15,colorama==0.3.9,coverage==3.7.1,flake8==2.5.5,funcsigs==1.0.2,idna==2.7,lazy-object-proxy==1.3.1,libvirt-python==4.0.0,lockfile==0.12.2,mccabe==0.4.0,mock==1.0.1,pep8==1.7.1,pluggy==0.6.0,py==1.6.0,pyflakes==1.0.0,pylint==1.5.6,pytest==3.4.2,requests==2.19.1,requests-mock==1.5.2,six==1.11.0,urllib3==1.23,wrapt==1.10.11
coverage run-test-pre: PYTHONHASHSEED='1624183434'
coverage runtests: commands[0] | cp libcloud/test/secrets.py-dist libcloud/test/secrets.py
coverage runtests: commands[1] | coverage run --source=libcloud setup.py test
running pytest
running egg_info
writing dependency_links to apache_libcloud.egg-info/dependency_links.txt
writing apache_libcloud.egg-info/PKG-INFO
writing top-level names to apache_libcloud.egg-info/top_level.txt
writing requirements to apache_libcloud.egg-info/requires.txt
reading manifest file 'apache_libcloud.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'libcloud/test/secrets.py'
writing manifest file 'apache_libcloud.egg-info/SOURCES.txt'
running build_ext
============================= test session starts ==============================
platform linux2 -- Python 2.7.15rc1, pytest-3.4.2, py-1.6.0, pluggy-0.6.0
rootdir: /home/mraful/PycharmProjects/libcloud, inifile: pytest.ini
plugins: requests-mock-1.5.2
collected 6162 items / 16 errors

==================================== ERRORS ====================================
_____________ ERROR collecting libcloud/test/compute/test_bsnl.py ______________
.tox/coverage/local/lib/python2.7/site-packages/_pytest/python.py:411: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
.tox/coverage/local/lib/python2.7/site-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
.tox/coverage/local/lib/python2.7/site-packages/_pytest/assertion/rewrite.py:213: in load_module
    py.builtin.exec_(co, mod.__dict__)
libcloud/test/compute/test_bsnl.py:18: in <module>
    from libcloud.compute.drivers.bsnl import BSNLNodeDriver
libcloud/compute/drivers/bsnl.py:19: in <module>
    from libcloud.compute.drivers.dimensiondata import DimensionDataNodeDriver
E     File "/home/mraful/PycharmProjects/libcloud/libcloud/compute/drivers/dimensiondata.py", line 3070
E       def ex_list_ip_address_list(self, ex_network_domain: object) -> object:
E                                                          ^
E   SyntaxError: invalid syntax
______ ERROR collecting libcloud/test/compute/test_dimensiondata_v2_3.py _______
.tox/coverage/local/lib/python2.7/site-packages/_pytest/python.py:411: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
.tox/coverage/local/lib/python2.7/site-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
.tox/coverage/local/lib/python2.7/site-packages/_pytest/assertion/rewrite.py:213: in load_module
    py.builtin.exec_(co, mod.__dict__)
libcloud/test/compute/test_dimensiondata_v2_3.py:28: in <module>
    from libcloud.compute.drivers.dimensiondata import DimensionDataNodeDriver as DimensionData
E     File "/home/mraful/PycharmProjects/libcloud/libcloud/compute/drivers/dimensiondata.py", line 3070
E       def ex_list_ip_address_list(self, ex_network_domain: object) -> object:
E                                                          ^
E   SyntaxError: invalid syntax
______ ERROR collecting libcloud/test/compute/test_dimensiondata_v2_4.py _______
.tox/coverage/local/lib/python2.7/site-packages/_pytest/python.py:411: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
.tox/coverage/local/lib/python2.7/site-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
.tox/coverage/local/lib/python2.7/site-packages/_pytest/assertion/rewrite.py:213: in load_module
    py.builtin.exec_(co, mod.__dict__)
libcloud/test/compute/test_dimensiondata_v2_4.py:28: in <module>
    from libcloud.compute.drivers.dimensiondata import DimensionDataNodeDriver as DimensionData
E     File "/home/mraful/PycharmProjects/libcloud/libcloud/compute/drivers/dimensiondata.py", line 3070
E       def ex_list_ip_address_list(self, ex_network_domain: object) -> object:
E                                                          ^
E   SyntaxError: invalid syntax
____________ ERROR collecting libcloud/test/compute/test_indosat.py ____________
.tox/coverage/local/lib/python2.7/site-packages/_pytest/python.py:411: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
.tox/coverage/local/lib/python2.7/site-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
.tox/coverage/local/lib/python2.7/site-packages/_pytest/assertion/rewrite.py:213: in load_module
    py.builtin.exec_(co, mod.__dict__)
libcloud/test/compute/test_indosat.py:18: in <module>
    from libcloud.compute.drivers.indosat import IndosatNodeDriver
libcloud/compute/drivers/indosat.py:22: in <module>
    from libcloud.compute.drivers.dimensiondata import DimensionDataNodeDriver
E     File "/home/mraful/PycharmProjects/libcloud/libcloud/compute/drivers/dimensiondata.py", line 3070
E       def ex_list_ip_address_list(self, ex_network_domain: object) -> object:
E                                                          ^
E   SyntaxError: invalid syntax
_______ ERROR collecting libcloud/test/compute/test_internetsolutions.py _______
.tox/coverage/local/lib/python2.7/site-packages/_pytest/python.py:411: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
.tox/coverage/local/lib/python2.7/site-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
.tox/coverage/local/lib/python2.7/site-packages/_pytest/assertion/rewrite.py:213: in load_module
    py.builtin.exec_(co, mod.__dict__)
libcloud/test/compute/test_internetsolutions.py:18: in <module>
    from libcloud.compute.drivers.internetsolutions import InternetSolutionsNodeDriver
libcloud/compute/drivers/internetsolutions.py:22: in <module>
    from libcloud.compute.drivers.dimensiondata import DimensionDataNodeDriver
E     File "/home/mraful/PycharmProjects/libcloud/libcloud/compute/drivers/dimensiondata.py", line 3070
E       def ex_list_ip_address_list(self, ex_network_domain: object) -> object:
E                                                          ^
E   SyntaxError: invalid syntax
____________ ERROR collecting libcloud/test/compute/test_medone.py _____________
.tox/coverage/local/lib/python2.7/site-packages/_pytest/python.py:411: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
.tox/coverage/local/lib/python2.7/site-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
.tox/coverage/local/lib/python2.7/site-packages/_pytest/assertion/rewrite.py:213: in load_module
    py.builtin.exec_(co, mod.__dict__)
libcloud/test/compute/test_medone.py:18: in <module>
    from libcloud.compute.drivers.medone import MedOneNodeDriver
libcloud/compute/drivers/medone.py:22: in <module>
    from libcloud.compute.drivers.dimensiondata import DimensionDataNodeDriver
E     File "/home/mraful/PycharmProjects/libcloud/libcloud/compute/drivers/dimensiondata.py", line 3070
E       def ex_list_ip_address_list(self, ex_network_domain: object) -> object:
E                                                          ^
E   SyntaxError: invalid syntax
_____________ ERROR collecting libcloud/test/compute/test_ntta.py ______________
.tox/coverage/local/lib/python2.7/site-packages/_pytest/python.py:411: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
.tox/coverage/local/lib/python2.7/site-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
.tox/coverage/local/lib/python2.7/site-packages/_pytest/assertion/rewrite.py:213: in load_module
    py.builtin.exec_(co, mod.__dict__)
libcloud/test/compute/test_ntta.py:18: in <module>
    from libcloud.compute.drivers.ntta import NTTAmericaNodeDriver
libcloud/compute/drivers/ntta.py:22: in <module>
    from libcloud.compute.drivers.dimensiondata import DimensionDataNodeDriver
E     File "/home/mraful/PycharmProjects/libcloud/libcloud/compute/drivers/dimensiondata.py", line 3070
E       def ex_list_ip_address_list(self, ex_network_domain: object) -> object:
E                                                          ^
E   SyntaxError: invalid syntax
________ ERROR collecting libcloud/test/loadbalancer/test_brightbox.py _________
libcloud/test/loadbalancer/test_brightbox.py:21: in <module>
    from libcloud.loadbalancer.drivers.brightbox import BrightboxLBDriver
libcloud/loadbalancer/drivers/brightbox.py:27: in <module>
    class BrightboxLBDriver(Driver):
libcloud/loadbalancer/drivers/brightbox.py:44: in BrightboxLBDriver
    'least-connections': Algorithm.LEAST_CONNECTIONS
E   AttributeError: type object 'Algorithm' has no attribute 'LEAST_CONNECTIONS'
________ ERROR collecting libcloud/test/loadbalancer/test_cloudstack.py ________
libcloud/test/loadbalancer/test_cloudstack.py:15: in <module>
    from libcloud.loadbalancer.drivers.cloudstack import CloudStackLBDriver
libcloud/loadbalancer/drivers/cloudstack.py:24: in <module>
    class CloudStackLBDriver(CloudStackDriverMixIn, Driver):
libcloud/loadbalancer/drivers/cloudstack.py:34: in CloudStackLBDriver
    'leastconn': Algorithm.LEAST_CONNECTIONS
E   AttributeError: type object 'Algorithm' has no attribute 'LEAST_CONNECTIONS'
____ ERROR collecting libcloud/test/loadbalancer/test_dimensiondata_v2_3.py ____
libcloud/test/loadbalancer/test_dimensiondata_v2_3.py:22: in <module>
    from libcloud.loadbalancer.drivers.dimensiondata \
libcloud/loadbalancer/drivers/dimensiondata.py:38: in <module>
    class DimensionDataLBDriver(Driver):
libcloud/loadbalancer/drivers/dimensiondata.py:54: in DimensionDataLBDriver
    'LEAST_CONNECTIONS': Algorithm.LEAST_CONNECTIONS,
E   AttributeError: type object 'Algorithm' has no attribute 'LEAST_CONNECTIONS'
____ ERROR collecting libcloud/test/loadbalancer/test_dimensiondata_v2_4.py ____
libcloud/test/loadbalancer/test_dimensiondata_v2_4.py:22: in <module>
    from libcloud.loadbalancer.drivers.dimensiondata \
libcloud/loadbalancer/drivers/dimensiondata.py:38: in <module>
    class DimensionDataLBDriver(Driver):
libcloud/loadbalancer/drivers/dimensiondata.py:54: in DimensionDataLBDriver
    'LEAST_CONNECTIONS': Algorithm.LEAST_CONNECTIONS,
E   AttributeError: type object 'Algorithm' has no attribute 'LEAST_CONNECTIONS'
___________ ERROR collecting libcloud/test/loadbalancer/test_gce.py ____________
libcloud/test/loadbalancer/test_gce.py:23: in <module>
    from libcloud.loadbalancer.drivers.gce import (GCELBDriver)
libcloud/loadbalancer/drivers/gce.py:27: in <module>
    DEFAULT_ALGORITHM = Algorithm.RANDOM
E   AttributeError: type object 'Algorithm' has no attribute 'RANDOM'
__________ ERROR collecting libcloud/test/loadbalancer/test_gogrid.py __________
libcloud/test/loadbalancer/test_gogrid.py:26: in <module>
    from libcloud.loadbalancer.drivers.gogrid import GoGridLBDriver
libcloud/loadbalancer/drivers/gogrid.py:58: in <module>
    class GoGridLBDriver(BaseGoGridDriver, Driver):
libcloud/loadbalancer/drivers/gogrid.py:68: in GoGridLBDriver
    'least connect': Algorithm.LEAST_CONNECTIONS
E   AttributeError: type object 'Algorithm' has no attribute 'LEAST_CONNECTIONS'
________ ERROR collecting libcloud/test/loadbalancer/test_rackspace.py _________
libcloud/test/loadbalancer/test_rackspace.py:29: in <module>
    from libcloud.loadbalancer.drivers.rackspace import RackspaceLBDriver, \
libcloud/loadbalancer/drivers/rackspace.py:284: in <module>
    class RackspaceLBDriver(Driver, OpenStackDriverMixin):
libcloud/loadbalancer/drivers/rackspace.py:308: in RackspaceLBDriver
    'RANDOM': Algorithm.RANDOM,
E   AttributeError: type object 'Algorithm' has no attribute 'RANDOM'
___________ ERROR collecting libcloud/test/loadbalancer/test_slb.py ____________
libcloud/test/loadbalancer/test_slb.py:22: in <module>
    from libcloud.loadbalancer.drivers.slb import SLBDriver, \
libcloud/loadbalancer/drivers/slb.py:88: in <module>
    'wrr': Algorithm.WEIGHTED_ROUND_ROBIN,
E   AttributeError: type object 'Algorithm' has no attribute 'WEIGHTED_ROUND_ROBIN'
________ ERROR collecting libcloud/test/loadbalancer/test_softlayer.py _________
libcloud/test/loadbalancer/test_softlayer.py:24: in <module>
    from libcloud.loadbalancer.drivers.softlayer import SoftlayerLBDriver
libcloud/loadbalancer/drivers/softlayer.py:69: in <module>
    class SoftlayerLBDriver(Driver):
libcloud/loadbalancer/drivers/softlayer.py:76: in SoftlayerLBDriver
    'LEAST_CONNECTIONS': Algorithm.LEAST_CONNECTIONS,
E   AttributeError: type object 'Algorithm' has no attribute 'LEAST_CONNECTIONS'
!!!!!!!!!!!!!!!!!!! Interrupted: 16 errors during collection !!!!!!!!!!!!!!!!!!!
========================== 16 error in 24.90 seconds ===========================
ERROR: InvocationError for command '/home/mraful/PycharmProjects/libcloud/.tox/coverage/bin/coverage run --source=libcloud setup.py test' (exited with code 2)
___________________________________ summary ____________________________________
ERROR:   py2.7: commands failed
ERROR:  pypypy: InterpreterNotFound: pypy
ERROR:  pypypy3: InterpreterNotFound: pypy3
ERROR:  py3.4: InterpreterNotFound: python3.4
ERROR:  py3.5: InterpreterNotFound: python3.5
ERROR:   py3.6: commands failed
  checks: commands succeeded
ERROR:   lint: commands failed
ERROR:   pylint: commands failed
ERROR:  integration: InterpreterNotFound: 
ERROR:   coverage: commands failed
